export const FETCH_BENEFICIARIES = "FETCH_BENEFICIARIES";
export const FETCH_VOLUNTEERS = "FETCH_VOLUNTEERS";
export const FETCH_PANCHAYATS = "FETCH_PANCHAYATS";
export const FETCH_MANDALS = "FETCH_MANDALS";
export const FETCH_PINCODES = "FETCH_PINCODES";

export const FETCH_BENEFICIARIES_ERROR = "FETCH_BENEFICIARIES_ERROR";
export const FETCH_VOLUNTEERS_ERROR = "FETCH_VOLUNTEERS_ERROR";
export const FETCH_PANCHAYATS_ERROR = "FETCH_PANCHAYATS_ERROR";
export const FETCH_MANDALS_ERROR = "FETCH_MANDALS_ERROR";
export const FETCH_PINCODES_ERROR = "FETCH_PINCODES_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const AUTH_ERROR = "AUTH_ERROR";

